'use strict';
const $=id=>document.getElementById(id),token=document.querySelector('meta[name="local-token"]').content;
let files=[],inspection=null,result=null,picture=null,examplePeriod=null,exampleKind=null;
async function api(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':token},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Błąd pomiaru');return data;}
async function run(fn){$('error').hidden=true;document.querySelectorAll('input,button,select').forEach(e=>e.disabled=true);$('status').textContent='Trwa analiza…';try{await fn();$('status').textContent='Gotowe.';}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('status').textContent='Sprawdź komunikat.';}finally{document.querySelectorAll('input,button,select').forEach(e=>e.disabled=false);}}
function list(id,items){$(id).replaceChildren(...items.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));}
function clear(){result=null;inspection=null;picture=null;files=[];examplePeriod=null;exampleKind=null;$('result').hidden=true;$('preview-section').hidden=true;$('measurement').hidden=true;$('demo-note').hidden=true;}
async function preview(){inspection=await api('/api/images/inspect',{file:files[0]});picture=new Image();await new Promise((resolve,reject)=>{picture.onload=resolve;picture.onerror=reject;picture.src=inspection.preview;});for(const id of ['target','reference']){$(id).replaceChildren(...inspection.stars.map((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Źródło ${i+1} · x=${s.x}, y=${s.y}${s.flags.length?' · uwaga':''}`;return o;}));}if(inspection.stars.length>1)$('reference').selectedIndex=1;$('quality').textContent=`${inspection.name} · ${inspection.width} × ${inspection.height} px · ${inspection.stars.length} kandydatów (maks. 100). Tło: ${inspection.background.toFixed(1)}, szum: ${inspection.noise.toFixed(1)}. Jednostki oryginalnego obrazu.`;list('warnings',inspection.warnings);$('preview-section').hidden=false;$('measurement').hidden=files.length<2||!inspection.scientific;drawSky();}
function drawSky(){if(!picture)return;const c=$('sky');c.width=picture.width;c.height=picture.height;const ctx=c.getContext('2d');ctx.drawImage(picture,0,0);const sx=c.width/inspection.width,sy=c.height/inspection.height;inspection.stars.forEach((s,i)=>{ctx.strokeStyle=i===Number($('target').value)?'#86dfc4':i===Number($('reference').value)?'#8babf6':s.flags.length?'#ff7272':'#edc77f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x*sx,s.y*sy,Math.max(5,Number($('radius').value)*sx),0,2*Math.PI);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='12px sans-serif';ctx.fillText(i+1,s.x*sx+7,s.y*sy-7);});}
function invalidate(){result=null;$('result').hidden=true;drawSky();}
['target','reference','radius','gain','saturation','calibrated'].forEach(id=>$(id).addEventListener('change',invalidate));
$('files').addEventListener('change',()=>run(async()=>{const chosen=[...$('files').files];clear();if(!chosen.length)return;if(chosen.length>160||chosen.reduce((s,f)=>s+f.size,0)>24000000)throw Error('Limit: 160 zdjęć i 24 MB łącznie.');for(const f of chosen){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f);});files.push({name:f.name,data});}$('calibrated').checked=false;await preview();}));
async function loadFolder(example){clear();const d=await api('/api/images/folder',example?{example}:{});files=d.files;await preview();if(example){examplePeriod=d.period;exampleKind=example;for(const k of ['target','reference'])$(k).value=inspection.stars.findIndex(s=>Math.hypot(s.x-d[k].x,s.y-d[k].y)<3);$('gain').value=d.gain;$('saturation').value=d.saturation;$('radius').value=d.radius;$('calibrated').checked=true;$('demo-note').textContent=({variable:'Symulacja: zmienna jasność lewej gwiazdy.',constant:'Symulacja: obie wybrane gwiazdy są stałe; widoczny jest szum pomiarowy.',saturated:'Symulacja: trzy klatki mają prześwietlony obiekt. Pomiar powinien je pominąć i podać przyczynę.'})[example]+' Pliki: '+d.folder;$('demo-note').hidden=false;}else{$('calibrated').checked=false;}drawSky();}
$('demo').addEventListener('click',()=>run(()=>loadFolder('variable')));
$('constant').addEventListener('click',()=>run(()=>loadFolder('constant')));
$('saturated').addEventListener('click',()=>run(()=>loadFolder('saturated')));
$('folder').addEventListener('click',()=>run(()=>loadFolder(null)));
$('measure').addEventListener('click',()=>run(async()=>{result=null;$('result').hidden=true;const target=inspection.stars[Number($('target').value)],reference=inspection.stars[Number($('reference').value)];if(!target||!reference)throw Error('Najpierw wybierz dwa źródła.');result=await api('/api/images/series',{files,target,reference,gain:$('gain').value,saturation:$('saturation').value,radius:$('radius').value,calibrated:$('calibrated').checked});$('result-info').textContent=`Pomiary: ${result.points.length}/${files.length}. Pasmo: ${result.band}. Mniejsze magnitudo oznacza jaśniejszy obiekt względem odniesienia.`;list('result-warnings',result.warnings);list('rejected',result.rejected.map(r=>`${r.name}: ${r.reason}`));$('result').hidden=false;drawCurve();}));
function drawCurve(){const c=$('curve'),ctx=c.getContext('2d'),p=result.points;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#b8c2d8';ctx.font='14px sans-serif';if(!p.length){ctx.fillText('Brak poprawnych pomiarów — sprawdź przyczyny poniżej.',30,80);return;}let t0=p[0].time,t1=p[p.length-1].time;const low=Math.min(...p.map(v=>v.magnitude-v.error))-.02,high=Math.max(...p.map(v=>v.magnitude+v.error))+.02;const X=t=>65+(t-t0)/Math.max(t1-t0,1e-8)*800,Y=m=>25+(m-low)/(high-low)*225;ctx.strokeStyle='#46536b';ctx.strokeRect(65,25,800,225);for(let i=0;i<5;i++){const m=low+(high-low)*i/4;ctx.fillText(m.toFixed(3),6,Y(m)+4);}ctx.fillText(`JD UTC ${t0.toFixed(6)} → ${t1.toFixed(6)}`,200,283);ctx.strokeStyle='#86dfc4';ctx.fillStyle='#86dfc4';for(const v of p){ctx.beginPath();ctx.moveTo(X(v.time),Y(v.magnitude-v.error));ctx.lineTo(X(v.time),Y(v.magnitude+v.error));ctx.stroke();ctx.beginPath();ctx.arc(X(v.time),Y(v.magnitude),3,0,2*Math.PI);ctx.fill();}}
function download(text,name,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('download').onclick=()=>{if(result)download(result.csv,'krzywa-ze-zdjec.csv','text/csv;charset=utf-8');};$('report').onclick=()=>{if(result)download(JSON.stringify(result,null,2),'pomiar-zdjec.json','application/json');};

$('to-main').onclick=()=>{if(!result||!result.points.length)return;sessionStorage.setItem('timdr-image-curve',JSON.stringify({text:result.csv,period:examplePeriod,example:exampleKind,band:result.band}));window.location.assign('/');};
